apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myoperators.deployer.shreyas.com
spec:
  group: deployer.shreyas.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: myoperators
    singular: myoperator
    kind: MyOperator
    shortNames:
      - myop
